project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**"
    - "!tr/**"

  resources:
    - assets/lang-toggle.js
    - lang-toggle.html


website:
  title: "Murat Seyhan, Data Scientist"
  navbar:
    right:
      - about.qmd
      - href: "#"
        text: TR   # <-- JS bunu gerçek linke çevirecek
      - icon: github
        href: https://github.com/mseyhan
      - icon: linkedin
        href: https://linkedin.com/in/muratseyhan
      - icon: twitter
        href: https://twitter.com/false9ry
  favicon: favicon.ico
  open-graph: true

lang: en

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header:
      - lang-toggle.html
