project:
  type: website
  output-dir: ../docs/tr
  render:
    - "*.qmd"
    - "posts/**"
  resources:
    - assets/lang-toggle.js

website:
  title: "Murat Seyhan, Data Scientist"
  navbar:
    right:
      - about.qmd
      - href: "#"
        text: EN   # <-- JS bunu gerçek linke çevirecek
      - icon: github
        href: https://github.com/mseyhan
      - icon: linkedin
        href: https://linkedin.com/in/muratseyhan
      - icon: twitter
        href: https://twitter.com/false9ry
  favicon: ../../favicon.ico
  open-graph: true

lang: tr

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: ../styles.css
    include-in-header:
      - ../lang-toggle.html
